#! /bin/bash

# usage:
# $ ./run_server_test.sh

CANDC_CLIENT_BIN=$BOXER_DIR/bin/soap_client
CANDC_CLIENT_OPT="--url $BOXER_SOAP_SERVER"

check_str() {
	read s
	if [[ $s == "% this file was generated by the following command(s):" ]]; then 
		echo "1"
	else 
		echo "0"
	fi
}

echo "Test" |
$CANDC_CLIENT_BIN $CANDC_CLIENT_OPT |  
check_str > /dev/stdout
